### ISSUE TITLE
Windows Glulxe and Windows Git close after showing the bibliographical information of A·L·I·E·N

### ISSUE THREAD

**Issue by sukiletxe** [DavidKinder/Windows-Glk#10] opened 2020-09-27 11:04 UTC
Hello,
I cannot play a Spanish Game called A·L·I·E·N. After opening it and showing the bibliographical information, both Windows Git and Windows Glulxe close without showing any error on screen. I also tried opening the game with the command line but it didn't work properly, and no error was shown in console either. According to a forum post, the game worked in some older glulxe version. Gargoile works fine, but there reviewing text is more difficult.

[The game is available here](https://github.com/ricpelo/alien/releases/download/180720/Alien_EE_180720.zip), and [here is its source code](https://github.com/ricpelo/alien/), if it can help.

I can try to debug what's happening if you provide me with some instructions.

Thanks!

**Comment by DavidKinder** [comment] 2020-10-07 09:15
Fixed by commit c31f2b2bbc8039d345b638fbd0532c0df60fb82b

**Comment by DavidKinder** [comment] 2020-10-07 09:17
The problem is that the game is calling glk_request_timer_events(0) before any window has opened. This shouldn't do anything, but because no windows are open, it leads to an internal error in Windows Glk. I have committed a fix for this which will be in the next release. The workaround in the meantime would be to not call glk_request_timer_events(0) during start-up before any windows open - all the call would do is stop any timers which aren't running anyway during initialization.

**Closed** 2020-10-07 09:17 UTC
